### PR TITLE
Added some neat verbosity

### PR DESCRIPTION
**Pull request by hydrophis-spiralis**
Neat tqdm progress bar instead of just print function. :)

### CODE REVIEW

**Comment by shreyasgm** [comment]
Thanks so much for the PR! 

This would definitely have been a neat addition, but `tqdm` still has some issues it needs to address before it's mature enough to be used in packages IMO. Examples - [1](https://github.com/tqdm/tqdm/issues/394) and others described [here](https://github.com/tqdm/tqdm#faq-and-known-issues). 

Further, if you're using the package in Jupyter notebook, you'd have to explicitly import `tqdm_notebook` instead of `tqdm` for it to work. You could solve that using `tqdm.autonotebook` but then it doesn't work on JupyterLab in my experience. Do you know how other packages address these issues?

**Comment by hydrophis-spiralis** [comment]
I use tqdm.tqdm for a quite a lot of time, aside of some issues In jupyter notebooks(similar to issue you linked) it works fine. Moreover, it seems to be best python package available, however, there is another progress bar package https://github.com/Erotemic/progiter which I have no experience with.
On tqdm.tqdm with Jupiter-notebook - it works and it outputs progress bar to standard output stream in text form. Maybe not so pretty as javascript generated by tqdm.tqdm_notebook, but it works.

**Comment by shreyasgm** [comment]
I can imagine KeyboardInterrupts being common while using py-ecomplexity. `tqdm` prints on multiple lines on Jupyter notebooks after KeyboardInterrupts if you don't using `tqdm_notebook` explicitly (as explained [here](https://github.com/tqdm/tqdm/issues/375) and [here](https://stackoverflow.com/questions/42212810/tqdm-in-jupyter-notebook)). I'll merge this if we can solve this issue using `tqdm.autonotebook`, while maintaining functionality for JupyterLab.

Also, `verbose` needs to be boolean, and the case for `verbose=False` needs to be handled.

**Comment by hydrophis-spiralis** [comment]
I totally agree on `tqdm` issue.

As for `verbose`, lot of frameworks have verbosity as integer - it usually controls level of verbosity.

**Pull request closed without merging**
